### ISSUE TITLE
UTF-8 Characters Missing or Incorrect

### ISSUE THREAD

**Issue by hirakujira** [omundy/givememydata#1]
The function clean_html function in data_converter.php may causes UTF-8 characters become blank or incorrect characters. For example, some Chinese names can't display.

![_2__give_me_my_data_on_facebook](https://cloud.githubusercontent.com/assets/358647/4917124/e5e1ac38-64e0-11e4-8aa2-ecb4d93ce609.png)

**Comment by omundy** [comment]
Any idea why? Could you add details about how you experienced the issue?

**Comment by hirakujira** [comment]
I found that it caused by

<pre>$string = str_replace(
        array(chr(145), chr(146), chr(147), chr(148), chr(150), chr(151), chr(133)),
        array("'", "'", '"', '"', '-', '--', '...'),
        $string);</pre>

For example, ASCII 148 = 0x94
And this Chinese character : http://www.fileformat.info/info/unicode/char/8521/index.htm is 0xE8 0x94 0xA1 in UTF-8 (hex) format.
So, the 0x94 of the Chinese char will be replaced.
