### ISSUE TITLE
can't download "music" after downloading "me"

### ISSUE THREAD

**Issue by deanmalmgren** [omundy/givememydata#2]
I was just experimenting with your app and wasn't able to authorize permission to download "music" after authorizing permission to download "me". From my brief playing around with an unrelated facebook app the past few days, I'm guessing this is because, when you authenticate you have to authorize all permissions simultaneously, but I could be way off on that.

Anyway, I just thought I'd give you a heads up.

**Comment by omundy** [comment]
Hi, thanks for the note. Are you talking about the live version or the one I've published here on Github?

**Comment by deanmalmgren** [comment]
The one that was on the live version.

**Comment by omundy** [comment]
Ah, yes there is an issue. Facebook has not allowed me to access those permissions per their new API 2.0 submission policy. I suppose I should just take the thing offline because they still haven't replied to my requests.

**Comment by deanmalmgren** [comment]
Good luck. The new app submission stuff is...how to put it...delightful?

**Comment by omundy** [comment]
Thanks. It's good and bad. They finally are making apps accountable. But on the other hand they can edit out the apps that are critical of the platform itself. There is no free speech online when you are dependent upon a master.
